# Generated by Django 6.0 on 2025-12-16 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nome', max_length=150, verbose_name='Nome')),
                ('image', models.ImageField(blank=True, db_column='imagem', null=True, upload_to='menu_items/', verbose_name='Imagem')),
                ('price', models.DecimalField(db_column='preco', decimal_places=2, max_digits=8, verbose_name='Preco')),
                ('description', models.TextField(blank=True, db_column='descricao', verbose_name='Descricao')),
                ('estimated_time', models.PositiveIntegerField(db_column='tempo_estimado', help_text='Tempo em minutos', verbose_name='Tempo estimado')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, to='catalog.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Item do menu',
                'verbose_name_plural': 'Itens do menu',
                'db_table': 'tb_item_menu',
            },
        ),
    ]
