# Generated by Django 6.0 on 2025-12-16 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_menuitem_created_at_menuitem_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='category',
            new_name='category_id',
        ),
        migrations.CreateModel(
            name='MenuItemIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(db_column='quantidade', default=1, verbose_name='Quantidade')),
                ('ingredient_id', models.ForeignKey(db_column='id_ingrediente', on_delete=django.db.models.deletion.PROTECT, to='catalog.ingredient', verbose_name='Ingrediente')),
                ('menu_item_id', models.ForeignKey(db_column='id_item_menu', on_delete=django.db.models.deletion.CASCADE, to='catalog.menuitem', verbose_name='Item do menu')),
            ],
        ),
    ]
