# Generated by Django 6.0 on 2025-12-16 20:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_category_menuitem_category_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitemingredient',
            options={'verbose_name': 'Ingrediente do item do menu', 'verbose_name_plural': 'Ingredientes do item do menu'},
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='criado_em', default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='id_criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='atualizado_em', verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='menuitemingredient',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='id_atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por'),
        ),
        migrations.AlterUniqueTogether(
            name='menuitemingredient',
            unique_together={('menu_item_id', 'ingredient_id')},
        ),
        migrations.AlterModelTable(
            name='menuitemingredient',
            table='tb_item_menu_ingredientes',
        ),
    ]
