# Generated by Django 6.0 on 2025-12-16 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_additional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='criado_em', verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='atualizado_em', verbose_name='Atualizado em')),
                ('additional_id', models.ForeignKey(db_column='id_adicional', on_delete=django.db.models.deletion.PROTECT, to='catalog.additional', verbose_name='Adicional')),
                ('created_by', models.ForeignKey(blank=True, db_column='id_criado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('menu_item_id', models.ForeignKey(db_column='id_item_menu', on_delete=django.db.models.deletion.CASCADE, to='catalog.menuitem', verbose_name='Item do menu')),
                ('updated_by', models.ForeignKey(blank=True, db_column='id_atualizado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Adicional do item do menu',
                'verbose_name_plural': 'Adicionais do item do menu',
                'db_table': 'tb_item_menu_adicionais',
                'unique_together': {('menu_item_id', 'additional_id')},
            },
        ),
    ]
